services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5001:5001
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:5433/ || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 60s

  minio-local:
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
    restart: always
    container_name: minio-local
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    environment:
      - 'MINIO_ROOT_USER:${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD:${MINIO_ROOT_PASSWORD}'

    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001
    command: 'minio server /data --console-address :9001'

  createbuckets:
    image: minio/mc:RELEASE.2023-11-15T22-45-58Z-cpuv1
    depends_on:
      - minio-local
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/bucket-filehub;
      /usr/bin/mc policy set public myminio/bucket-filehub;
      exit 0;
      "

volumes:
  minio_storage: {}
