import Head from "next/head";
import Header from "./Header";

const Layout = ({children}: {children: React.ReactNode}): React.ReactNode => {
    return (
        <>
            <Head>
                <title>theGoodCorner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="main-content">{children}</main>
        </>
    )
}
export default Layout;